<Project>
  <ItemGroup Condition="'$(MSBuildProjectName)' != 'Nexhire.Analyzers' And !$(MSBuildProjectName.Contains('Tests'))">
    <ProjectReference Include="$(MSBuildThisFileDirectory)src\Nexhire.Analyzers\Nexhire.Analyzers.csproj">
      <OutputItemType>Analyzer</OutputItemType>
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>
</Project>
